# 0: default mode
# 1: master mode
# 2: slave mode
# 3: full slave mode
# 其它, 看代码里面的注释
sync_mode: 4

fps: 60


prophesee:
  # 0: record
  # 1: play
  record_or_play: 0
  file_dir: "../resource/"
  file_to_play: "../resource/date/time.raw"